### ISSUE TITLE
important news

### ISSUE THREAD

**Issue by matthew4444** [GameCraftPE/LobbyCore#1]
i think i might close the universalmine repo , should i? 
im thinking the project is going dead :(
if u cant help, any developer wont probalby help :(
plz respond

**Comment by dries-c** [comment]
why you contact me here
i also think universalmine will go dead

**Comment by matthew4444** [comment]
becuase i didnt know where else to get u :(

**Comment by dries-c** [comment]
Ok here is my email coenendries3@gmail.com

**Comment by matthew4444** [comment]
thx
