### ISSUE TITLE
GameCraftPC - Error

### ISSUE THREAD

**Issue by ghost** [GameCraftPE/LobbyCore#2]
Sorry that I write here but there is not Issues section on GameCraftPC resource.

[ip] logged out due to Connection closed

PC MC: Access Token can not be null or empty

**Comment by ghost** [comment]
I fixed this but I can not login. I have always Login timeout.

**Comment by dries-c** [comment]
i will update that soon but now i will open the issues on that plugin

**Comment by ghost** [comment]
Okay. Thx.

**Comment by dries-c** [comment]
plz reopen this on that plugin

**Comment by dries-c** [comment]
its fixed
